server:
  port: 8085

feign:
  okhttp:
    enabled: true # 开启OKHttp功能

hm:
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
  db:
    host: localhost
    port: 33306
    database: hm-trade
    un: root
    pw: 123456