server:
  port: 8082
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100

feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true

hm:
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
  db:
    host: localhost
    port: 33306
    database: hm-cart
    un: root
    pw: 123456

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # 是否设置资源请求方式作为资源名称